name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install huggingface_hub

    - name: Deploy to Hugging Face Spaces
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_SPACE: "Minatoz997/Chirostore"
      run: |
        python -c "
        import os
        from huggingface_hub import HfApi, create_repo
        
        # Initialize HF API
        api = HfApi(token=os.environ['HF_TOKEN'])
        
        # Create or get space
        try:
            api.create_repo(
                repo_id=os.environ['HF_SPACE'],
                repo_type='space',
                space_sdk='docker',
                exist_ok=True
            )
            print(f'✅ Space {os.environ[\"HF_SPACE\"]} ready')
        except Exception as e:
            print(f'Space might already exist: {e}')
        
        # Upload all files
        try:
            api.upload_folder(
                folder_path='.',
                repo_id=os.environ['HF_SPACE'],
                repo_type='space',
                ignore_patterns=['.git*', '__pycache__*', '*.pyc', '.env*', 'test_*'],
                commit_message=f'Deploy from GitHub: {os.environ.get(\"GITHUB_SHA\", \"latest\")[:7]}'
            )
            print(f'✅ Successfully deployed to https://huggingface.co/spaces/{os.environ[\"HF_SPACE\"]}')
        except Exception as e:
            print(f'❌ Deployment failed: {e}')
            exit(1)
        "

    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 **Deployment Successful!**\n\n✅ Your changes have been deployed to Hugging Face Spaces:\n🔗 **Live URL**: https://huggingface.co/spaces/Minatoz997/Chirostore\n\n📖 **API Documentation**: https://minatoz997-chirostore.hf.space/docs\n🔍 **Health Check**: https://minatoz997-chirostore.hf.space/health'
          })